# -*- coding: utf-8 -*-
"""AEGIS_1D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVGBPwyz9QDAqyK9KIto09gWrqmBIzEL
"""

'''
This file is only the AEGIS solver, with no method benchmarking
'''

# Initializing all the functions here to simplify the layout

import numpy as np
import matplotlib.pyplot as plt
import os
from numba import njit

# I'm just gonna take the old code and paste it to here

@njit
def first_order_solution(rho, mom, E, dt, dx):
    # I'm literally just going to copy paste from Chris' original LF code
    # Convert conservative -> primitive
    rho, u, p = cons_to_prim(rho, mom, E)

    # Compute fluxes at every cell
    F = compute_flux(rho, mom, E, p)

    # Lax-Friedrichs update: averaged neighbors + central flux difference
    rho[1:-1] = 0.5 * (rho[2:] + rho[:-2]) - dt / (2 * dx) * (F[0, 2:] - F[0, :-2])
    mom[1:-1] = 0.5 * (mom[2:] + mom[:-2]) - dt / (2 * dx) * (F[1, 2:] - F[1, :-2])
    E[1:-1]   = 0.5 * (E[2:]   + E[:-2])   - dt / (2 * dx) * (F[2, 2:] - F[2, :-2])

    # Apply boundary conditions (copy neighbor so waves pass through)
    rho, mom, E = apply_bcs(rho, mom, E)

    return rho, mom, E

@njit
def reconstruct_5th_order(u):
  uL = (2*u[:-4] - 13*u[1:-3] + 47*u[2:-2] + 27*u[3:-1] - 3*u[4:])/60
  uR = (2*u[4:] - 13*u[3:-1] + 47*u[2:-2] + 27*u[1:-3] - 3*u[:-4])/60
  return uR, uL

@njit
def minmod3(a, b, c):
  # Minmod limiter used by the MC reconstruction.
  same_sign = (a * b > 0.0) & (a * c > 0.0)
  limited = np.sign(a) * np.minimum(
      np.abs(a),
      np.minimum(np.abs(b), np.abs(c))
  )
  return np.where(same_sign, limited, 0.0)

@njit
def reconstruct_MUSCL_MC(q):
  # 2nd-order MUSCL reconstruction with an MC slope limiter
  dq_left = q[1:-1] - q[:-2]
  dq_center = 0.5 * (q[2:] - q[:-2])
  dq_right = q[2:] - q[1:-1]

  slope = minmod3(
      2.0 * dq_left,
      dq_center,
      2.0 * dq_right
  )

  # Match the N-4 layout returned by reconstruct_5th_order.
  center = q[2:-2]
  slope = slope[1:-1]

  q_left = center - 0.5 * slope
  q_right = center + 0.5 * slope
  return q_left, q_right

@njit
def shock_Detector(p):

  # This is an extended form of the JST edge sensor

  sensor_num = (p[:-4] - 4*p[1:-3] + 6*p[2:-2] - 4*p[3:-1] + p[4:])
  sensor_den = (p[:-4] + 4*p[1:-3] + 6*p[2:-2] + 4*p[3:-1] + p[4:])

  sensor = np.abs(sensor_num/sensor_den)

  return sensor

def interpolation(rho_L, rho_R, mom_L, mom_R, E_L, E_R):
    u_L = mom_L / rho_L
    u_R = mom_R / rho_R

    p_L = (gamma - 1) * (E_L - 0.5 * rho_L * u_L**2)
    p_R = (gamma - 1) * (E_R - 0.5 * rho_R * u_R**2)

    # Compute fluxes at every cell

    F_L = compute_flux(rho_L, mom_L, E_L, p_L)
    F_R = compute_flux(rho_R, mom_R, E_R, p_R)

    U_left = np.array([rho_R[:-1], mom_R[:-1], E_R[:-1]])
    U_right  = np.array([rho_L[1:],  mom_L[1:],  E_L[1:]])

    # Compute speed of sound for BOTH sides
    c_L = np.sqrt(gamma * p_L / rho_L)
    c_R = np.sqrt(gamma * p_R / rho_R)

    F_half = np.zeros_like(U_left)

    # Variables look similar, but are diff in this case, sorry for poor naming

    uL = u_R[:-1]
    uR = u_L[1:]

    cL = c_R[:-1]
    cR = c_L[1:]

    pL = p_R[:-1]
    pR = p_L[1:]

    rhoL = rho_R[:-1]
    rhoR = rho_L[1:]

    FL = F_R[:, :-1]
    FR = F_L[:, 1:]

    EL = E_R[:-1]
    ER = E_L[1:]

    # Taken from the Toro book, pdf page 353

    S_L = np.minimum(uL - cL, uR - cR)
    S_R = np.maximum(uL + cL, uR + cR)

    S_star = (pR - pL + rhoL*uL*(S_L-uL) - rhoR*uR*(S_R-uR))/(
        rhoL*(S_L-uL) - rhoR*(S_R-uR)
    )

    # Setting up the D_star stuff

    D_star = np.zeros((3, len(S_star)))

    D_star[0, :] = 0
    D_star[1, :] = 1
    D_star[2, :] = S_star

    # Getting the star state fluxes

    F_star_L_num = S_star * (S_L*U_left - FL) + S_L*(pL+rhoL*(S_L-uL)*(S_star-uL))*D_star
    F_star_L_den = S_L - S_star

    F_star_R_num = S_star * (S_R*U_right - FR) + S_R*(pR+rhoR*(S_R-uR)*(S_star-uR))*D_star
    F_star_R_den = S_R - S_star

    F_star_L = F_star_L_num/F_star_L_den
    F_star_R = F_star_R_num/F_star_R_den

    left = (0 <= S_L)
    left_star = (S_L <= 0) & (0 <= S_star)
    right_star = (S_star <= 0) & (0 <= S_R)
    right = (0 >= S_R)

    F_half[:, left] = FL[:, left]
    F_half[:, right] = FR[:, right]

    F_half[:, left_star] = F_star_L[:, left_star]
    F_half[:, right_star] = F_star_R[:, right_star]

    return F_half

@njit
# Function to convert conservative -> primitive variables
def cons_to_prim(rho, mom, E):
    u = mom / rho
    p = (gamma - 1) * (E - 0.5 * rho * u**2)
    return rho, u, p

@njit
# Function to convert primitive -> conservative variables
def prim_to_cons(rho, u, p):
    mom = rho * u
    E = p / (gamma - 1) + 0.5 * rho * u**2
    return rho, mom, E

@njit
# Function to compute fluxes
def compute_flux(rho, mom, E, p):
    F = np.zeros((3, len(rho)))
    F[0, :] = mom
    F[1, :] = mom**2 / rho + p
    F[2, :] = (E + p) * mom / rho
    return F

def rhs(rho, mom, E, dt, blend):

    drho = np.zeros_like(rho)
    dmom = np.zeros_like(mom)
    dE = np.zeros_like(E)

    positive_floor = 1e-12
    center = slice(2, -2)

    U = np.vstack((rho, mom, E))

    # Convert conservative variables to primitive variables
    rho, u, p = cons_to_prim(rho, mom, E)

    shockArray_p = shock_Detector(p)
    shockArray_rho = shock_Detector(rho)

    shockArray = np.maximum(shockArray_p, shockArray_rho)

    # MUSCL-MC Reconstruction

    rho_L_MC, rho_R_MC = reconstruct_MUSCL_MC(rho)
    u_L_MC, u_R_MC = reconstruct_MUSCL_MC(u)
    p_L_MC, p_R_MC = reconstruct_MUSCL_MC(p)

    # This just an insurance against unphysical states
    rho_L_MC = np.where(
        rho_L_MC > positive_floor, rho_L_MC, rho[center]
    )
    rho_R_MC = np.where(
        rho_R_MC > positive_floor, rho_R_MC, rho[center]
    )
    p_L_MC = np.where(
        p_L_MC > positive_floor, p_L_MC, p[center]
    )
    p_R_MC = np.where(
        p_R_MC > positive_floor, p_R_MC, p[center]
    )

    rho_L_MC, mom_L_MC, E_L_MC = prim_to_cons(
        rho_L_MC, u_L_MC, p_L_MC
    )
    rho_R_MC, mom_R_MC, E_R_MC = prim_to_cons(
        rho_R_MC, u_R_MC, p_R_MC
    )

    F_half_MC = interpolation(
        rho_L_MC, rho_R_MC,
        mom_L_MC, mom_R_MC,
        E_L_MC, E_R_MC
    )

    # Fifth-order primitive-variable reconstruction

    rho_L_5, rho_R_5 = reconstruct_5th_order(rho)
    u_L_5, u_R_5 = reconstruct_5th_order(u)
    p_L_5, p_R_5 = reconstruct_5th_order(p)

    # Just a safety net on negative predicted values from the reconstruction

    rho_L_5 = np.where(
        rho_L_5 > positive_floor, rho_L_5, rho[center]
    )
    rho_R_5 = np.where(
        rho_R_5 > positive_floor, rho_R_5, rho[center]
    )
    p_L_5 = np.where(
        p_L_5 > positive_floor, p_L_5, p[center]
    )
    p_R_5 = np.where(
        p_R_5 > positive_floor, p_R_5, p[center]
    )

    rho_L_5, mom_L_5, E_L_5 = prim_to_cons(
        rho_L_5, u_L_5, p_L_5
    )
    rho_R_5, mom_R_5, E_R_5 = prim_to_cons(
        rho_R_5, u_R_5, p_R_5
    )

    F_half5 = interpolation(
        rho_L_5, rho_R_5,
        mom_L_5, mom_R_5,
        E_L_5, E_R_5
    )

    # First-order local Rusanov flux
    F = compute_flux(rho, mom, E, p)

    c = np.sqrt(gamma * p / rho)
    wave_speed = np.abs(u) + c

    a_face = np.maximum(
        wave_speed[2:-3],
        wave_speed[3:-2]
    )

    F_half1 = (
        0.5 * (F[:, 2:-3] + F[:, 3:-2])
        - 0.5 * a_face[None, :]
          * (U[:, 3:-2] - U[:, 2:-3])
    )

    # Fifth order in smooth regions
    F_half_hi = F_half5

    # Original fourth/first-order blend beside shocks
    F_half_lo = 0.75 * F_half_MC + 0.25 * F_half1

    # Convert the cell-centered sensor to one shared value at each face
    edge_sensor = np.maximum(
        shockArray[:-1],
        shockArray[1:]
    )

    # Gaussian curve for the sensor scale

    sensor_scale = 0.02

    shockWeight = 1.0 - np.exp(
        -(edge_sensor / sensor_scale)**2
    )

    # Blend fluxes before taking their divergence
    F_half = (
        (1.0 - shockWeight) * F_half_hi
        + shockWeight * F_half_lo
    )

    drho[3:-3] = -(F_half[0, 1:] - F_half[0, :-1]) / dx
    dmom[3:-3] = -(F_half[1, 1:] - F_half[1, :-1]) / dx
    dE[3:-3] = -(F_half[2, 1:] - F_half[2, :-1]) / dx

    return drho, dmom, dE

@njit
def apply_bcs(rho, mom, E):
    # Applying BCs
    # Going to rely on a global variable here to help out with deciding BCs
    # Based on chosen IC

    rho[:3] = rho[3]
    rho[-3:] = rho[-4]

    E[:3] = E[3]
    E[-3:] = E[-4]

    if bc == "normal":
        # Just going with simple 0 gradient in/outflows

        mom[:3] = mom[3]
        mom[-3:] = mom[-4]

    elif bc == "reflect":
        # This will just have the variables reflect back at the boundary
        # This would be no in/outflow
        mom[:3] = -mom[3]
        mom[-3:] = -mom[-4]

    return rho, mom, E


def time_integration(rho, mom, E, blend, dt):
    # Convert conservative -> primitive
    rho, u, p = cons_to_prim(rho, mom, E)

    # Compute speed of sound
    c = np.sqrt(gamma * p / rho)

    # k1 state
    rho0, mom0, E0 = apply_bcs(rho, mom, E)
    k1_rho, k1_mom, k1_E = rhs(rho0, mom0, E0, dt, blend)
    #print("k1 done")

    # k2 state
    rho2 = rho + 0.5 * dt * k1_rho
    mom2 = mom + 0.5 * dt * k1_mom
    E2   = E   + 0.5 * dt * k1_E
    rho2, mom2, E2 = apply_bcs(rho2, mom2, E2)
    k2_rho, k2_mom, k2_E = rhs(rho2, mom2, E2, dt/2, blend)
    #print("k2 done")

    # k3 state
    rho3 = rho + 0.5 * dt * k2_rho
    mom3 = mom + 0.5 * dt * k2_mom
    E3   = E   + 0.5 * dt * k2_E
    rho3, mom3, E3 = apply_bcs(rho3, mom3, E3)
    k3_rho, k3_mom, k3_E = rhs(rho3, mom3, E3, dt/2, blend)
    #print("k3 done")

    # k4 state
    rho4 = rho + dt * k3_rho
    mom4 = mom + dt * k3_mom
    E4   = E   + dt * k3_E
    rho4, mom4, E4 = apply_bcs(rho4, mom4, E4)
    k4_rho, k4_mom, k4_E = rhs(rho4, mom4, E4, dt, blend)
    #print("k4 done")

    # Final update
    rho = rho + dt * (k1_rho + 2*k2_rho + 2*k3_rho + k4_rho) / 6
    mom = mom + dt * (k1_mom + 2*k2_mom + 2*k3_mom + k4_mom) / 6
    E   = E   + dt * (k1_E   + 2*k2_E   + 2*k3_E   + k4_E) / 6

    rho, mom, E = apply_bcs(rho, mom, E)

    return rho, mom, E

  # Constants
createPlot = True  # Set to True to create plots
gamma = 1.4  # Ratio of specific heats
Nx = 256     # Number of grid points
L = 1.0      # Domain length
dx = L / (Nx - 1)  # Spatial step
CFL = 0.4   # Courant number, going with the lit

# Spatial grid
x = np.linspace(0, L, Nx)

# Initialize all arrays
rho = np.zeros(Nx)  # Density
p = np.zeros(Nx)    # Pressure
u = np.zeros(Nx)    # Velocity
E = np.zeros(Nx)    # Total energy
mom = np.zeros(Nx)  # Momentum

# Also have to initialize everything for the plots later
fig = None
ax1 = ax2 = ax3 = None
title_rho = title_u = title_p = None

line_rho_blend = line_rho_first = None

line_u_blend = line_u_first = None

line_p_blend = line_p_first = None

# Select initial conditions
IC_type = "shu-osher"  # Options: "sod", "shu-osher", "lax_tube", "woodward", "Einfeldt", "Gauss"

# Create output directory if it doesn't exist
output_dir = "results_lf"
os.makedirs(output_dir, exist_ok=True)

# Initial conditions
if IC_type == "sod":
    # Sod shock tube

    rho[:] = 1.0
    rho[x >= 0.5] = 0.125  # Right side density

    p[:] = 1.0
    p[x >= 0.5] = 0.1  # Right side pressure

    u[:] = 0.0  # Velocity (zero everywhere)

    bc = "normal"

    t_final = 0.2  # Final time


elif IC_type == "shu-osher":
    # Shu-Osher problem

    # Left state (post-shock)
    rho_l = 27/7
    p_l = 31/3
    u_l = 2.629369

    # Right state (pre-shock with oscillations)
    rho_r = 1.0 + 0.2 * np.sin(50 * x)  # Density with sine wave
    p_r = np.ones(Nx)
    u_r = np.zeros(Nx)

    # Combine left and right states
    shock_pos = 0.1
    rho = np.where(x < shock_pos, rho_l, rho_r)
    p = np.where(x < shock_pos, p_l, p_r)
    u = np.where(x < shock_pos, u_l, u_r)

    bc = "normal"

    t_final = 0.18 # Final time

elif IC_type == "lax_tube":
    # The Lax Shock Tube problem

    # Left state
    rho_l = 0.445
    p_l = 3.528
    u_l = 0.689

    # Right state
    rho_r = 0.5
    p_r = 0.571
    u_r = 0.0

    # Combining left and right states
    shock_pos = 0.5

    rho = np.where(x < shock_pos, rho_l, rho_r)
    p = np.where(x < shock_pos, p_l, p_r)
    u = np.where(x < shock_pos, u_l, u_r)

    bc = "normal"

    t_final = 0.14

elif IC_type == "woodward":
    # This is the Woodward-Colella test problem

    rho[:] = 1.0
    u[:] = 0.0
    p_l = 1000.0
    p_mid = 0.01
    p_r = 100.0

    shock_pos1 = 0.1
    shock_pos2 = 0.9

    p = np.where(x > shock_pos1, p_mid, p_l)
    p[x > shock_pos2] = p_r

    bc = "reflect"

    t_final = 0.038

elif IC_type == "Einfeldt":

    rho[:] = 1.0
    p[:] = 0.4
    u_l = -2.0
    u_r = 2.0

    shock_pos = 0.5

    u = np.where(x < shock_pos, u_l, u_r)

    bc = "normal"

    t_final = 0.15

elif IC_type == "Gauss":
    # This is used for the convergence plot, but is just generally a good smooth
    # problem to test

    rho = 1.0 + 0.1*np.exp(-((x - 0.5)**2)/(2*0.1**2))
    u = 1.0
    p = 1.0

    bc = "normal"

    t_final = 0.5

# Convert to conservative variables
E = p / (gamma - 1) + 0.5 * rho * u**2  # Total energy
mom = rho * u  # Momentum

# Time integration loop
t = 0.0
step = 0

# Setting up the comparison for the two methods
rho_blend = rho.copy()
mom_blend = mom.copy()
E_blend = E.copy()

while t < t_final:

    print(f"Time: {t:.6f}, Timestep Num: {step}")

    # Convert conservative -> primitive (just for negative check)
    rho_blend, u_blend, p_blend = cons_to_prim(rho_blend, mom_blend, E_blend)

    # Compute speed of sound (for each method)
    c_blend = np.sqrt(gamma * p_blend / rho_blend)

    # Compute time step based on CFL condition (for each method)
    dt_blend = CFL * dx / np.max(np.abs(u_blend) + c_blend)

    # Choose the time-step which gets us exactly to t_final

    dt = min(dt_blend, t_final - t)

    # Check for unphysical states
    if np.any(rho_blend <= 0) or np.any(p_blend <= 0):
      print("[BLENDED] Unphysical starting state at time n", t, step)
      break

    # Time integration

    rho_blend, mom_blend, E_blend = time_integration(rho_blend, mom_blend, E_blend, True, dt)

    # Set to per 100 timesteps, but reduce if you're testing something
    if step%100 == 0:

        # Convert to primitive variables for plotting
        rho_plot_blend, u_plot_blend, p_plot_blend = cons_to_prim(rho_blend, mom_blend, E_blend)

        if createPlot:

            # Creating the actual figure
            fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(15, 5))

            # Density plot
            line_rho_blend, = ax1.plot(x, np.zeros_like(x), color='r', label="AEGIS Density")
            ax1.set_xlabel("x")
            ax1.set_ylabel("Density")
            title_rho = ax1.set_title("Density Profile (t=0.000)")
            ax1.grid()
            leg1 = ax1.legend()

            # Velocity plot
            line_u_blend, = ax2.plot(x, np.zeros_like(x), color='r', label="AEGIS Velocity")
            ax2.set_xlabel("x")
            ax2.set_ylabel("Velocity")
            title_u = ax2.set_title("Velocity Profile (t=0.000)")
            ax2.grid()
            leg2 = ax2.legend()

            # Pressure plot
            line_p_blend, = ax3.plot(x, np.zeros_like(x), color='r', label="AEGIS Pressure")
            ax3.set_xlabel("x")
            ax3.set_ylabel("Pressure")
            title_p = ax3.set_title("Pressure Profile (t=0.000)")
            ax3.grid()
            leg3 = ax3.legend()

            # Not gonna close the graph to keep reusing it
            fig.tight_layout()
            fig.savefig(os.path.join(output_dir, f'step_{step:04d}.png'))


            createPlot = False

        else:
            line_rho_blend.set_ydata(rho_plot_blend)
            title_rho.set_text(f"Density Profile (t={t:.3f})")

            line_u_blend.set_ydata(u_plot_blend)
            title_u.set_text(f"Velocity Profile (t={t:.3f})")

            line_p_blend.set_ydata(p_plot_blend)
            title_p.set_text(f"Pressure Profile (t={t:.3f})")

            ax1.relim(); ax1.autoscale_view()
            ax2.relim(); ax2.autoscale_view()
            ax3.relim(); ax3.autoscale_view()

            fig.savefig(os.path.join(output_dir, f'step_{step:04d}.pdf'))


    t += dt
    step += 1

# Use the actual final state, not the last 50-step plotting checkpoint
rho_plot_blend, u_plot_blend, p_plot_blend = cons_to_prim(
    rho_blend, mom_blend, E_blend
)

line_rho_blend.set_ydata(rho_plot_blend)
title_rho.set_text(f"Density Profile (t={t:.3f})")

line_u_blend.set_ydata(u_plot_blend)
title_u.set_text(f"Velocity Profile (t={t:.3f})")

line_p_blend.set_ydata(p_plot_blend)
title_p.set_text(f"Pressure Profile (t={t:.3f})")

ax1.relim(); ax1.autoscale_view()
ax2.relim(); ax2.autoscale_view()
ax3.relim(); ax3.autoscale_view()

fig.savefig(os.path.join(output_dir, f'step_{step:04d}.png'))